#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by ChatGPT.
##  You can regenerate the official script by running `gradle wrapper`.
##
##############################################################################

APP_HOME=$(cd "${0%/*}" && pwd)

DEFAULT_JVM_OPTS=""

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

JAVA_EXE=java

exec "$JAVA_EXE" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

